# Example Home Assistant Automations
# These are example automations showcasing common patterns

- id: 'example_motion_lights'
  alias: 'Example: Motion Activated Lights'
  description: 'Turn on lights when motion is detected'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: light.turn_on
      target:
        entity_id: light.living_room_main
      data:
        brightness_pct: 75

- id: 'example_schedule_lights'
  alias: 'Example: Evening Light Schedule'
  description: 'Turn on evening lights at sunset'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  action:
    - service: light.turn_on
      target:
        area_id: living_room
      data:
        brightness_pct: 50

- id: 'example_device_notification'
  alias: 'Example: Low Battery Notification'
  description: 'Notify when device battery is low'
  trigger:
    - platform: numeric_state
      entity_id: sensor.phone_battery_level
      below: 20
  condition:
    - condition: time
      after: '09:00:00'
      before: '22:00:00'
  action:
    - service: notify.mobile_app
      data:
        title: "Low Battery Alert"
        message: "Your phone battery is at {{ states('sensor.phone_battery_level') }}%"
