# Example Home Assistant Configuration File
# This is a minimal example configuration for demonstration purposes

# Basic Home Assistant configuration
homeassistant:
  name: Home
  latitude: 37.7749
  longitude: -122.4194
  elevation: 0
  unit_system: metric
  currency: USD
  country: US
  time_zone: America/Los_Angeles

# Load frontend
frontend:

# Enable configuration panel
config:

# Enable the map panel
map:

# Enable mobile app integration
mobile_app:

# Enable history and logbook
history:
logbook:

# Enable system health
system_health:

# Include automations and scripts
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example integrations
weather:
  - platform: met
    name: Local Weather

# Example groups
group:
  living_room:
    name: "Living Room"
    entities:
      - light.living_room_main
      - switch.living_room_fan

# Example sensors
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

# Example binary sensors
binary_sensor:
  - platform: workday
    country: US
