# Example Home Assistant Scenes
# These capture the state of multiple entities for quick activation

- name: "Movie Night"
  entities:
    light.living_room_main:
      state: on
      brightness: 10
      color_temp: 454
    light.living_room_accent:
      state: off
    media_player.living_room_tv:
      state: on
      source: "Netflix"

- name: "Dinner Time"
  entities:
    light.dining_room_chandelier:
      state: on
      brightness: 180
      color_temp: 350
    light.kitchen_under_cabinet:
      state: on
      brightness: 255

- name: "Work From Home"
  entities:
    light.office_desk:
      state: on
      brightness: 255
      color_temp: 250
    climate.office:
      state: heat_cool
      temperature: 72
    switch.office_fan:
      state: on

- name: "Away Mode"
  entities:
    light.front_porch:
      state: on
      brightness: 128
    climate.main_thermostat:
      state: away
    alarm_control_panel.home_security:
      state: armed_away
